export const skills = {
    languages: [
        "Javascript",
        "Typescript",
        "HTML",
        "CSS",
        "PHP",
        "SQL",
        "SASS",
    ],
    tools: [
        "React / JSX",
        "Node",
        "NPM",
        "Jest",
        "Vue",
        "CirceCI",
        "Cypress",
        "Yarn",
        "GraphQL",
        "MySQL",
        "Lighthouse",
        "Git",
        "Github",
        "Gitlab",
    ],
    aws: [
        "Lambda",
        "SNS",
        "SQS",
        "AppSync",
        "Cloudfront",
        "Route53",
        "S3",
        "IAM",
        "Ec2",
        "API Gateway",
        "Cloudwatch",
    ],
    cms: [
        "Wordpress",
        "AEM",
    ],
    misc: [
        "Testing / automation",
        "RDB design / normalisation",
        "i18n",
        "a11y",
        "SEO",
    ],
}